package betix.core.config;

public enum ConfigKey {
    asDaemon,
    lockFile,
    browser,
    placeBet,
    sikuliMinSimilarity,
    imageDir,
    teamImageDir,
    imageExt,
    siteName,
    siteUrl,
    username,
    password,
    teamNameSeparator,
    messageBoxColor,
    minBetStake,
    balanceRegEx,
    historyMatchInfoLinkRegEx,
    matchInfoPendingState,
    matchInfoLoseState,
    matchInfoWinState,
    matchInfoStakeRegEx,
    matchInfoCoefficientRegEx,
    matchInfoWiningRegEx,
    matchInfoEventRegEx,
    matchInfoDateRegEx,
    matchInfoDateTimeRegEx,
    useFibonacciForStakes,
    cronExpression,
    dateFormat,
    siteHistoryUrl,
    imgTimeout,
    waitTimeBeforeAction,
    accountInfo

}
